### ISSUE TITLE
cod should not offer to learn a command unless it has something to learn

### ISSUE THREAD

**Issue by zachriggle** [dim-an/cod#12]
`cod` should not offer to learn a command if there is nothing to learn / there are no completable flags detected.

```
┌──> /Users/zachriggle/.../script --help
└─── cod: learn this command? [yn?] > y
cod: learned completions:
```

**Comment by dim-an** [comment]
You should keep in mind that cod doesn't capture output of `--help` command from the terminal (I don't know the way to do it), it has to launch last command itself.

So cod doesn't know if there is any completions beforehand. :(
