### ISSUE TITLE
Use `command cod` in generated scripts

### ISSUE THREAD

**Issue by NightMachinary** [dim-an/cod#23]
I already have a `cod` alias, and so the current generated scripts don't work for me. It's far more reliable to use `command cod ...` in the generated scripts. This is especially true since `cod` is a 3-lettered word, and so the probability of it already being in use is not negligible.

PS: I am using `command cod init $$ zsh | sd '\bcod\b' 'command cod'` as a workaround currently.

**Comment by dim-an** [comment]
Thanks for report. Going to fix it on this week.
