### ISSUE TITLE
cod cannot auto-learn itself

### ISSUE THREAD

**Issue by zachriggle** [dim-an/cod#3]
COD appears unable to learn its own subcommands

```
$ cod list
11	/Users/zachriggle/bin/cod --help
$ cod --help<tab>
--help     --version
```

**Comment by dim-an** [comment]
Sad but true.

I wrote `cod` to complete a great number of python `argparse` scripts that I have so it has a special support for python argparse with its subcommands and cannot parse other subcommands.

1. I think I have an idea how `cod` can extract subcommands. Looks like it would work for `cod` `docker` and some other tools I'm going to implement it when I have time.

2. If you want to have good code completion for cod right now please note that `kingpin` library that is used by `cod` has its own `bash`/`zsh` [completion](https://github.com/alecthomas/kingpin/tree/v2.2.6#bashzsh-shell-completion). So you can add to your `.zshrc`:
```
cod --completion-script-zsh
```
I didn't include this into `cod` init script beacuse it felt like cheating :)
