### ISSUE TITLE
fish shell support

### ISSUE THREAD

**Issue by lordlycastle** [dim-an/cod#37]
When you do `cod init --help` it lists that you can specify `fish` as an argument but no script is returned when `fish` is used.

So does this tool have FISH shell support? If not I would like to request it as it is very popular shell.

Thanks!

**Comment by dim-an** [comment]
First version of `cod` supported `fish` since it was shell on my local machine those days.

But then I decided to focus my efforts on `zsh` and `bash` (and switched  to `zsh` myself).

Anyway a agree support of `fish` should be added.

**Comment by lordlycastle** [comment]
Awesome. So what is needed for this? How does this work? Do we need a hook to feed it all the commands we run and it filters for anything with `-h|--help`? 

Would help in any way I can!

**Comment by dim-an** [comment]
You can take a look at [existing implementation](https://github.com/dim-an/cod/blob/e08812e3568d91dac7b0f71870893b8c73a694b2/shells/shells.go#L175) for `bash`.

We need to implement an interface `ShellScriptGenerator` that generates a bunch of shell code.
  - `GetPreamble` returns initialization code that defines hooks and helper functions
  -  `GenerateCompletions` is used to generate shell code that notifies shell about completions for newly learned command
  -  `ResetCommand` removes `cod` completions from givven command.

First of all we need a hook that is launched after command execution (check `__cod_postexec_bash`). This hook: 
  - gets last executed command
  - checks its exit status (we don't check commands with nonzero exitcode)
  - feed command into `cod api postexec ...` (this api call checks if call looks like help invocation and shows UI)
  - calls `cod api poll-updates` to poll updates (e.g. we learned new command from other terminal window and we want to get notification about it).
 
About `GeneratesCompletions`. This script doesn't actually feeds shell with bunch of learned flags. Instead it asks shell to use
`cod api complete-words` to get required completions. This api call unifies completion generation for all shells and can do complex logic while generating list of completions.
