### ISSUE TITLE
Unable to learn on macOS Big Sur (M1 chip)

### ISSUE THREAD

**Issue by cigoic** [dim-an/cod#44]
Hi,

Just tried to learn command help. But there is an error msg shown:

`__cod_add_completions:2: command not found: compdef`

Any idea? Thanks.

**Comment by dim-an** [comment]
Hey! Which shell and version do you use?

**Comment by cigoic** [comment]
macOS Big Sur's ZSH Terminal Version 2.11 (440).

**Comment by cigoic** [comment]
zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by dim-an** [comment]
You don't use `oh-my-zsh` or any other fancy zsh configuration, right?

`compdef` is a standard `zsh` function.

But you have to initialize completion system. It is done by function `compinit`. Try add to your `.zshrc` following lines (better to put them in the beginning of the file):
```
autoload -Uz compinit
compinit
```

Also you can check [zsh documentation](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Initialization).

**Comment by dim-an** [comment]
Great!
