### ISSUE TITLE
Which file to sync to share the learned completions between my machines?

### ISSUE THREAD

**Issue by IndianBoy42** [dim-an/cod#47]
I currently use YADM to sync all my configs, as well as my fish completions.

I would like to share the cod learned completions as well.

I am not sure which/if there is a file that I should sync, it seems like you store the completions in a sqlite database.

Thanks for any help

**Comment by dim-an** [comment]
`cod` stores all completions in `$HOME/.local/share/cod/db.sqlite3` by default. Though I would consider this file as implementation detail and I'm afraid that this file wasn't designed for syncing.

But you can try.

**Comment by dim-an** [comment]
I'm closing this issue for now. If you still have any questions please reopen.
