### ISSUE TITLE
cod fails to start on macOs

### ISSUE THREAD

**Issue by af-mikecrowe** [dim-an/cod#49]
Getting this error:

```
cod: error: server returned error: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

**Comment by dim-an** [comment]
Hi!
Did you built cod yourself or used prebuilt binaries?

**Comment by af-mikecrowe** [comment]
Prebuilt binaries

**Comment by dim-an** [comment]
Sorry for long reply. I don't have Mac at my myself, yesterday I had a chance to borrow it and updated release. Please check if it works for you.
